name: Test and Build

on:
    push:
        branches:
            - master


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install composer and dependencies
              uses: php-actions/composer@v6

            - name: Setup PHP with XDebug
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  coverage: xdebug

            - name: Run Unit Tests
              run: composer run test-unit
